version: '3.3'

services:

    api:
        image: montebal/laradev:php80-2204
        build:
            context: ../
            dockerfile: docker/dev.Dockerfile
        container_name: sound-trackdle-api
        ports:
            - "80:80"
        environment:
            XDEBUG_TRIGGER: "docker"
            PHP_IDE_CONFIG: "serverName=Docker"
        volumes:
            - ./../:/var/www/html
            - sound-trackdle-api-vendor:/var/www/html/vendor
        networks:
            sound-trackdle:

    mysql:
        image: mysql:8
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            MYSQL_ROOT_HOST: '%'
        ports:
            - ${SQL_PORT}:3306
        volumes:
            - sound-trackdle-db:/var/lib/mysql
        networks:
            sound-trackdle:

    phpmyadmin:
        image: phpmyadmin
        ports:
            - "90:80"
        links:
            - mysql:db
        networks:
            sound-trackdle:

volumes:
    sound-trackdle-db:
        external: false
    sound-trackdle-api-vendor:
        external: false

networks:
    sound-trackdle:
